version: '3.8'

services:
  mysqldb:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - brewery

  artemis:
    image: strohs/artemis-temurin11:2.24.0
    ports:
      - "61616:61616"
      - "8161:8161"
    environment:
      - ARTEMIS_USER=artemis
      - ARTEMIS_PASSWORD=artemis
      - ANONYMOUS_LOGIN=false
      - EXTRA_ARGS=--http-host 0.0.0.0 --relax-jolokia
    networks:
      - brewery

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - brewery

  eureka:
    image: strohs/brewery-eureka
    ports:
      - "8761:8761"
    environment:
      SPRING_ZIPKIN_BASEURL: http://zipkin
    networks:
      - brewery
    restart: on-failure

  config:
    image: strohs/brewery-config-server
    ports:
      - "8888:8888"
    depends_on:
      - eureka
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: true
    networks:
      - brewery
    restart: on-failure

  inventory-service:
    image: strohs/beer-inventory-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka
      - config
      - artemis
      - zipkin
      - mysqldb
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: true
      SPRING_PROFILES_ACTIVE: local-discovery, local, local-docker
#  Next 3 props are sources from cloud config server
#      SPRING_ZIPKIN_BASE_URL: http://zipkin:9411
#      SPRING.ARTEMIS.BROKER_URL: "tcp://artemis:61616"
#      SPRING_DATASOURCE_URL: "jdbc:mysql://mysqldb:3306/beerinventoryservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC"
    networks:
      - brewery
    restart: on-failure

  inventory-failover-service:
    image: strohs/beer-inventory-failover-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka
      - config
      - artemis
      - zipkin
      - mysqldb
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: true
      SPRING_PROFILES_ACTIVE: local-discovery, local, local-docker
      SPRING_ZIPKIN_BASE_URL: http://zipkin:9411
      SPRING_ZIPKIN_ENABLED: true
    networks:
      - brewery
    restart: on-failure

  beer-service:
    image: strohs/beer-service
    ports:
      - "8080:8080"
    depends_on:
      - eureka
      - config
      - artemis
      - zipkin
      - mysqldb
      - inventory-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: true
      SPRING_PROFILES_ACTIVE: local-discovery, local, local-docker
    networks:
      - brewery
    restart: on-failure

  order-service:
    image: strohs/beer-order-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka
      - config
      - artemis
      - zipkin
      - mysqldb
      - inventory-service
      - beer-service
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: true
      SPRING_PROFILES_ACTIVE: local-discovery, local, local-docker
      ORG_CJS_BEER_SERVICE_HOST: "http://beer-service:8080"
    networks:
      - brewery
    restart: on-failure

  brewery-gateway:
    image: strohs/brewery-gateway
    ports:
      - "9090:9090"
    depends_on:
      - eureka
      - zipkin
      - config
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: true
      SPRING_PROFILES_ACTIVE: local-discovery, local-docker
    networks:
      - brewery
    restart: on-failure

networks:
  brewery: